### ISSUE TITLE
Miku's TODOs

### ISSUE THREAD

**Issue by BackHDLP** [katniny/transsocial#6]
Just because I made this TODO-list doesn't mean I'm the only one who is allowed to work on all these. 
If you have more things, please file a new issue. these are just things im thinking of implementing

@katniny can you tell me if you're already yworking on any of these?

### Major Features
- [ ] Account deletion (in progress)
- [ ] basic builtin admin tools
- [ ] User banners
- [ ] Spoiler CW
- [x] Webapp Manifest (#5)

### Minor Features
- [ ] New lines
- [ ] Link to /userstudio from settings
- [ ] Mentions Notifications
- [x] add a no-script message (#2)

### Bugs
- [ ] usernames in the TransSocial Accounts section are misaligned
- [ ] The sidebar sometimes isn't the full height
- [ ] clicking the reply button boosts a note
- [ ] everything wrong with the margin and paddings in notes outside the main tl
- [ ] quoted posts are a set height

### Code Style
- [ ] formatting
- [ ] de-nesting
- [ ] early returns
- [ ] remove all the empty `else`s
- [x] Clean up QOTD (#1)

### Other
- [ ] consistent corner rounding
- [ ] contributing guide (in slow progress)
- [x] change github link to this repo (#3)
- [x] issue templates (#4)

### Major Features
- [ ] bring back favourites
- [ ] Multiple images
- [ ] reporting notes

### Minor Features
- [ ] Allow pasting images

**Comment by katniny** [comment]
im working on favorites
im not working on anything else on this list, though would love to help :)

**Comment by katniny** [comment]
i need to remember this exists when i dont know what to add lol
